config/routes.rb
Rails.application.routes.draw do
  root to: "site#about", as: :about

  get "blog", to: "blog#index",  as: :blog
  get "blog/:slug", to: "blog#show", as: :blog_post

  # Add channel for Facebook plugin performance
  # https://developers.facebook.com/blog/post/2011/08/02/how-to--optimize-social-plugin-performance/
  get "channel", to: "site#channel", as: :facebook_channel

  namespace :admin do
    match "/", to: "base#login", as: :login, via: [:get, :post]
    get "logout", to: "base#logout", as: :logout

    resources :admins
    resources :posts
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_many :posts, foreign_key: :author_id

  validates :name, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true
  has_secure_password

end

app/models/post.rb
class Post < ActiveRecord::Base
  default_scope { where(enabled: true).order(published_at: :desc) }

  belongs_to :author, class_name: "Admin"

  before_validation :update_slug

  validates :author, presence: true
  validates :title, presence: true
  validates :slug, presence: true, uniqueness: true
  validates :body, presence: true
  validates :abstract, presence: true

  # Publish post when it's enabled
  def enabled=(check)
    self.published_at ||= Time.now if check == "1"
    self[:enabled] = check
  end

private

  # Autogenerate and/or parameterize slug
  def update_slug
    self[:slug] = (slug&.presence || title&.presence)&.parameterize
  end

end

app/controllers/admin/admins_controller.rb
class Admin::AdminsController < Admin::BaseController

  def index
    @admins = Admin.all
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.create(admin_params)
    if @admin.valid?
      flash[:success] = "Admin created successfully."
      redirect_to admin_admins_path
    else
      render action: "new"
    end
  end

  def edit
    @admin = Admin.find params[:id]
  end

  def update
    @admin = Admin.find params[:id]

    if @admin.update_attributes(admin_params)
      flash[:success] = "Admin updated successfully."
      redirect_to admin_admins_path
    else
      render action: "edit"
    end
  end

  def destroy
    @admin = Admin.find(params[:id]).destroy
    flash[:success] = "Admin destroyed successfully."
    redirect_to admin_admins_path
  end

private

  def admin_params
    params.require(:admin).permit(:name, :username, :password, :password_confirmation)
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin, except: [:login]
  layout "admin"

  def login
    if request.post?
      if @admin = Admin.find_by_username(params[:admin][:username])
        if @admin.authenticate(params[:admin][:password])
          session[:admin_id] = @admin.id
          redirect_to session.delete(:admin_requested_url) || admin_posts_path
        else
          flash.now[:error] = "Your password is incorrect."
        end
      else
        flash.now[:error] = "There is no admin with that username."
      end
    end
  end

  def logout
    session[:admin_id] = nil
    redirect_to admin_login_path
  end

private

  def admin_params
    params.require(:admin).permit(:name, :username, :password, :password_confirmation)
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController

  def index
    @posts = Post.unscoped
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create post_params
    if @post.save
      flash[:success] = "Post created successfully."
      redirect_to admin_posts_path
    else
      render action: "new"
    end
  end

  def edit
    @post = Post.unscoped.find params[:id]
  end

  def update
    @post = Post.unscoped.find params[:id]
    if @post.update_attributes(post_params)
      flash[:success] = "Post updated successfully."
      redirect_to edit_admin_post_path(params[:id])
    else
      render action: "edit"
    end
  end

  def destroy
    @post = Post.unscoped.find(params[:id]).destroy
    flash[:success] = "Post destroyed successfully."
    redirect_to admin_posts_path
  end

private

  def post_params
    params.require(:post).permit(:author_id, :title, :slug, :body, :abstract, :meta_description, :meta_keywords, :enabled, :filepicker_url)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_admin
    @current_admin ||= Admin.find_by_id(session[:admin_id])
  end
  helper_method :current_admin

  def require_admin
    unless current_admin
      flash[:notice] = "You have to log in."
      session[:admin_requested_url] = request.url unless request.xhr?
      session[:admin_id] = nil
      redirect_to admin_login_path and return
    end
  end

end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post  = Post.find_by_slug params[:slug]
    @posts = Post.where.not slug: params[:slug]
  end

end

app/controllers/site_controller.rb
# A controller for all the static pages

class SiteController < ApplicationController

  def about
  end

  def channel
    render layout: false
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when :notice then "alert alert-info"
    when :success then "alert alert-success"
    when :error then "alert alert-error"
    when :alert then "alert alert-error"
    end
  end

  def human_date(date)
    suffix = case date.day
    when 1 then "st"
    when 2 || 22 then "nd"
    when 3 then "rd"
    else "th"
    end
    date.strftime("%A, %B %e#{suffix} %Y")
  end

  def nav_link_to(name, href, options = {})
    selected = [controller_name, action_name].join("#").match(/^#{options.delete(:selected)}/)
    options[:class] = "selected #{options[:class]}" if selected
    link_to name, href, options
  end

  def bg(photo_url)
    "background-image: url(#{photo_url});"
  end

  # OPTIMIZE
  # ...didn't really want to add the Filepicker gem just for these two methods
  def filepicker_image_tag(url, image_options = {}, image_tag_options = {})
    image_tag(filepicker_image_url(url, image_options), image_tag_options)
  end

  def filepicker_image_url(url, options = {})
    query_params = options.slice(:w, :h, :fit, :align, :crop, :format, :quality, :watermark, :watersize, :waterposition).to_query
    [url, "/convert?", query_params].join
  end

end

app/helpers/blog_helper.rb
module BlogHelper

  def markdown(text)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true,
      nowrap:true
    }
    Redcarpet::Markdown.new(Redcarpet::Render::HTML, options).render(text).html_safe
  end

end

app/views/admin/admins/_form.html.erb
<%= render partial: "layouts/errors", formats: [:html], locals: { klass: @admin } %>

<%= f.label :name %>
<%= f.text_field :name, class: "pure-input-1-2" %>

<%= f.label :username %>
<%= f.text_field :username, class: "pure-input-1-2" %>

<%= f.label :password %>
<%= f.password_field :password, class: "pure-input-1-2" %>

<%= f.label :password_confirmation, "Password Confirmation" %>
<%= f.password_field :password_confirmation, class: "pure-input-1-2" %>

<p>
  <%= f.submit "Save Admin", class: "pure-button pure-button-primary" %>
</p>

app/views/admin/admins/edit.html.erb
<% content_for :page_header do %>
	<h1>Edit Admin</h1>
<% end %>

<p>
	<%= link_to 'Back', admin_admins_path, class: 'pure-button' %>
</p>

<%= form_for [:admin, @admin], html: { class: 'pure-form pure-form-stacked' } do |f| %>
	<%= render partial: "form", formats: [:html], locals: { f: f } %>
<% end %>

app/views/admin/admins/index.html.erb
<% content_for :page_header do %>
  <h1>Admins</h1>
<% end %>

<p>
  <%= link_to new_admin_admin_path, class: 'pure-button pure-button-primary' do %>
    <i class="fa fa-plus"></i>
    New Admin
  <% end %>
</p>

<table class="pure-table pure-table-striped">
  <thead>
    <tr>
      <th>Login</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= link_to admin.name, edit_admin_admin_path(admin) %></td>
        <td>
          <%= button_to admin_admin_path(admin), method: :delete, data: { confirm: 'Are you sure?' }, class: 'pure-button' do %>
            <i class="fa fa-trash"></i>
            Delete
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/admins/new.html.erb
<% content_for :page_header do %>
	<h1>New Admin</h1>
<% end %>

<%= form_for [:admin, @admin], html: { class: 'pure-form pure-form-stacked' } do |f| %>
	<%= render partial: "form", formats: [:html], locals: { f: f } %>
<% end %>

app/views/admin/base/login.html.erb
<% content_for :page_header do %>
  <h1>Login</h1>
<% end %>

<%= form_for :admin, url: admin_login_path, html: { class: 'pure-form pure-form-aligned' } do |f| %>
  <fieldset>
    <div class="pure-control-group">
      <%= f.label :username, 'Username' %>
      <%= f.text_field :username %>
    </div>
    <div class="pure-control-group">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class="pure-controls">
      <%= f.submit 'Submit', class: 'pure-button pure-button-primary' %>
    </div>
  </fieldset>
<% end %>

app/views/admin/posts/_form.html.erb
<%= render partial: 'layouts/errors', formats: [:html], locals: { klass: @post } %>

<%= f.label :author, class: 'control-label' %>
<input type="text" value="<%= current_admin.name %>" disabled>
<%= f.hidden_field :author_id, value: current_admin.id %>

<%= f.label :filepicker_url, "Image" %>
<input
  type="filepicker"
  class="pure-button pure-button-primary"
  data-fp-apikey="AmJqL5MJUSbuPOJA7JD2Iz"
  data-fp-mimetypes="image/*"
  data-fp-container="modal"
  onchange="window.setFilepickerImage(event.fpfile.url)">

<% if false %>
<%= link_to 'Pick File', '#', id: 'filepicker_url', class: 'pure-button pure-button-primary' %>
<% end %>
<%= f.hidden_field :filepicker_url %>

<div id="post-image">
  <% if @post.filepicker_url.present? %>
    <%= image_tag("#{@post.filepicker_url}") %>
  <% end %>
</div>

<%= f.label :title %>
<%= f.text_field :title, class: 'pure-input-1' %>

<%= f.label :slug %>
<%= f.text_field :slug, class: 'pure-input-1' %>

<%= f.label :body %>
<%= f.text_area :body, class: 'pure-input-1' %>

<%= f.label :abstract %>
<%= f.text_area :abstract, class: 'pure-input-1' %>

<%= f.label :meta_description %>
<%= f.text_field :meta_description, class: 'pure-input-1' %>

<%= f.label :meta_keywords %>
<%= f.text_field :meta_keywords, class: 'pure-input-1' %>

<%= f.label :enabled, class: 'control-label' %>
<%= f.check_box :enabled, value: @post.enabled? %>

<p>
  <%= f.submit 'Save Post', class: 'pure-button pure-button-primary' %>
</p>

app/views/admin/posts/edit.html.erb
<% content_for :page_header do %>
	<h1>Edit Post</h1>
	<h2><%= @post.title %></h2>
<% end %>

<p>
	<%= link_to 'Back', admin_posts_path, class: 'pure-button' %>
</p>

<%= form_for [:admin, @post], html: { class: 'pure-form pure-form-stacked' } do |f| %>
	<%= render partial: "form", formats: [:html], locals: { f: f } %>
<% end %>

app/views/admin/posts/index.html.erb
<% content_for :page_header do %>
  <h1>Posts</h1>
  <h2>Blog posts on Humani.se</h2>
<% end %>

<p>
  <%= link_to new_admin_post_path, class: 'pure-button pure-button-primary' do %>
    <i class="fa fa-plus"></i>
    New Post
  <% end %>
</p>

<table class="pure-table pure-table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Enabled?</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, edit_admin_post_path(post) %></td>
        <td><%= post.author.name %></td>
        <td><%= post.enabled? ? "Yes" : "No" %></td>
        <td>
          <%= button_to admin_post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'pure-button' do %>
            <i class="fa fa-trash"></i>
            Delete
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/posts/new.html.erb
<% content_for :page_header do %>
	<h1>New Post</h1>
<% end %>

<p>
	<%= link_to 'Back', admin_posts_path, class: 'pure-button' %>
</p>

<%= form_for [:admin, @post], html: { class: 'pure-form pure-form-stacked' } do |f| %>
	<%= render partial: "form", formats: [:html], locals: { f: f } %>
<% end %>

app/views/blog/_sidebar.html.erb
<article>
  <%= link_to 'mailto:jeff@humani.se', id: 'me' do %>
    <%= content_tag :figure, nil, style: bg(asset_url('me.png')) %>
    <h3>Jeff Miller</h3>
  <% end %>

  <span class="blurb">Conducting code in the Bay -- Hella.</span>

  <div id="social-links">
    <%= link_to 'jeff@humani.se', 'mailto:jeff@humani.se', id: 'social-email' %>

    <% SOCIAL.each do |network, url| %>
      <%= link_to url, target: '_blank', class: network do %>
        <i class="hu-<%= network %>"></i>
      <% end %>
    <% end %>
  </div>

</article>

app/views/blog/index.html.erb
<section>
  <% @posts.each do |post| %>
    <%= content_tag :article, id: post.id, class: "post" do %>

      <!-- Figure + Date Info -->
      <%= link_to blog_post_path(post.slug), class: "post-thumbnail", style: bg(post.filepicker_url) do %>
        <%= content_tag :time, datetime: post.published_at.to_date.to_s do %>
          <small><%= post.published_at.strftime("%B") %></small>
          <big><%= post.published_at.day %></big>
          <small><%= post.published_at.year %></small>
        <% end %>
      <% end %>

      <!-- Content -->
      <div class="post-content">
        <%= link_to blog_post_path(post.slug) do %>
          <h2 wrap="bt-rl"><%= post.title %></h2>
        <% end %>
        <p><%= post.abstract.html_safe %></p>
        <%= link_to icon("fas", "ellipsis-h"), blog_post_path(post.slug) %>
      </div>

    <% end %>
  <% end %>
</section>

<aside>
  <%= render partial: "sidebar" %>
</aside>

app/views/blog/show.html.erb
<%= content_for :head do %>
  <meta itemprop="name" content="<%= @post.title %>">
  <meta itemprop="description" content="<%= @post.abstract %>">
  <meta itemprop="image" content="<%= @post.filepicker_url %>">
  <meta property="fb:admins" content="ibanez270dx"/>
  <meta property="og:title" content="<%= @post.title %>" />
  <meta property="og:description" content="<%= @post.meta_description %>">
  <meta property="og:url" content="<%= blog_post_url(@post.slug) %>" />
  <meta property="og:image" content="<%= @post.filepicker_url %>" />
  <meta property="og:type" content="article" />
  <meta property="og:site_name" content="Humani.se" />
<% end %>

<section>
  <article id="<%= @post.id %>" class="post">
    <%= content_tag :figure, style: bg(@post.filepicker_url) do %>
      <figcaption>
        <h1 wrap="bt" scale-font="0.055"><%= @post.title %></h1>
        <span>Posted on <%= human_date @post.published_at %></span>
      </figcaption>
    <% end %>
    <section class="post-content">
      <%= markdown @post.body %>
    </section>
  </article>

  <article class="comments">
    <h2>Comments</h2>
    <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES * * */
        var disqus_shortname = 'humanise';

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
  </article>
</section>

<aside>
  <%= render partial: 'sidebar' %>

  <article class="sidebar related-posts">
    <h4>Other Posts</h4>
    <% @posts.each do |post| %>
      <%= link_to post.title, blog_post_path(post.slug) %>
    <% end %>
  </article>

</aside>

app/views/layouts/_errors.html.erb
<% if klass.errors.any? %>
  <div class="error-messages">
    <h4>There are <%= klass.errors.count %> <%= "problems".pluralize(klass.errors.count) %> with the form:</h4>
    <ul>
      <% klass.errors.each do |field, error| %>
        <li><%= field.to_s.humanize %> <%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="flash-messages <%= flash_class(key) %>">
    <%= value %>
  </div>
<% end %>

app/views/layouts/_google_analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-109231703-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
</script>

app/views/layouts/_social_links.html.erb
<div id="social-links">
  <% SOCIAL.each do |network, url| %>
    <%= link_to url, target: '_blank', class: "hu-#{network}-cutout" do %>
      <i class="hu-<%= network %>"></i>
    <% end %>
  <% end %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html class="admin <%= "#{controller.controller_path.split('/').join(' ')} #{controller.action_name.gsub(/_/, '-')}" %>">
  <head>
    <title><%= @title || "Humani.se Admin" %></title>
    <%= stylesheet_link_tag "admin", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div id="layout">
      <!-- Menu toggle -->
      <a href="#menu" id="menuLink" class="menu-link">
        <!-- Hamburger icon -->
        <span></span>
      </a>

      <div id="menu">
        <div class="pure-menu pure-menu-open">
          <%= link_to 'Humani.se', admin_login_path, class: "pure-menu-heading" %>
          <ul>
            <% if current_admin %>
              <li><%= link_to 'Admins', admin_admins_path %></li>
              <li><%= link_to 'Posts', admin_posts_path %></li>
            <% end %>
          </ul>
        </div>
      </div>

      <div id="main">
        <div class="header">
          <%= yield :page_header %>
        </div>

        <div class="content">
          <%= render 'layouts/flash_messages' %>
          <%= yield %>
        </div>
      </div>
    </div>


    <script type="text/javascript" src="//api.filepicker.io/v1/filepicker.js"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="push-down">
  <head>
    <title><%= @title || "Humani.se" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= tag :link, rel: "icon", type: "image/png", href: "/favicon.png" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= render 'layouts/google_analytics' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= yield :head %>
  </head>
  <body class="<%= "#{controller.controller_path.split('/').join(' ')} #{controller.action_name.gsub(/_/, '-')}" %>">
    <div id="freelancing" data-turbolinks="false">
      <div>
        <%= link_to icon("fas", "times"), "#", class: "close" %>
        <span class="message">
          <%= icon "fas", "exclamation-triangle" %> &nbsp;Looking for my freelance work?
        </span>
        <span class="link">
          Check out <%= link_to "OverWine.io", "https://overwine.io", target: :_blank %>
        </span>
      </div>
    </div>
    <header>
      <nav>
        <%= link_to about_path do %>
          <h1>humani.se</h1>
          <%= image_tag('logo.png', class: 'nav-logo') %>
        <% end %>
        <%= nav_link_to 'About', about_path, selected: 'site#about' %>
        <%= nav_link_to 'Blog', blog_path, selected: 'blog#' %>
      </nav>
    </header>

    <main>
      <%= yield %>
    </main>

  </body>
</html>

app/views/site/about.html.erb
<h1>Hi. I'm a Software Engineer.</h1>

<article>
  <p>
    My name is Jeff Miller and I enjoy creating software. In particular, I enjoy
    exploring the ever evolving & challanging world of web and mobile
    application development. I am currently the lead Senior Full Stack Engineer over at
    <%= link_to "Cognoa", "https://www.cognoa.com", target: :blank %>,
    whose mission is to employ big data and machine learning to vastly improve
    early childhood detection of developmental disabilities including autism.
  </p>
  <p>
    I set up this website/testbed to share some of my projects, experiences,
    and thoughts on what I've learned over the years working and living in
    Silicon Valley. My hope is that something I share here can help you get
    inspired, solve something, or at least provide some insight about
    programming or whatever else I decide to write about.
  </p>
</article>

<footer>
  <%= render 'layouts/social_links' %>
</footer>

app/views/site/blog.html.erb
<article class="glass-box">
  <% @posts.each do |post| %>
    <div class="post" id="<%= post.id %>">
      <div class="header">
        <div class="calendar">
          <span class="month"><%= post.published_at.strftime('%B') %></span>
          <span class="day"><%= post.published_at.day %></span>
          <span class="year"><%= post.published_at.year %></span>
        </div>
        <h2><%= post.title %></h2>
      </div>
      <div class="body">
        <%= post.body %>
      </div>
    </div>
  <% end %>
</article>

<aside class="glass-box">
  <h3>Posts</h3>
  <ul>
    <li>Blah and blah</li>
    <li>Rails Stuff</li>
    <li>Ipsum Lorum</li>
  </ul>
</aside>

app/views/site/channel.html.erb
<script src="//connect.facebook.net/en_US/all.js"></script>

app/views/site/index.html.erb
<h1>Hi. I'm a Software Engineer.</h1>
<article class="glass-box">
  <p>
    My name is Jeff Miller and I enjoy creating software. Particularly, I like Ruby on Rails and exploring the world of web applications
    not only for desktop, but also for mobile. I am currently an engineer over at <%= link_to 'Funny or Die', 'http://www.funnyordie.com', target: '_blank' %>
    in the beautiful Bay Area of California.
  </p>
  <p>
    I've set up this website to act as not only a portfolio, but also a blog and test bed to share some of the projects I've worked on and things I've
    learned over the years. My hope is that something I share here can help, inspire, or at least provide some insight about programming or whatever
    else I decide to write about.
  </p>
</article>

<% content_for :footer do %>
  <ul class="social-icons">
    <li>
      <%= link_to 'http://github.com/ibanez270dx' do %>
        <%= image_tag('social-icons/github-off.png') %>
        <%= image_tag('social-icons/github-on.png') %>
      <% end %>
    </li>
    <li>
      <%= link_to 'http://twitter.com/ibanez270dx' do %>
        <%= image_tag('social-icons/twitter-off.png') %>
        <%= image_tag('social-icons/twitter-on.png') %>
      <% end %>
    </li>
    <li>
      <%= link_to 'http://www.linkedin.com/in/ibanez270dx' do %>
        <%= image_tag('social-icons/linkedin-off.png') %>
        <%= image_tag('social-icons/linkedin-on.png') %>
      <% end %>
    </li>
    <li>
      <%= link_to 'http://www.facebook.com/ibanez270dx' do %>
        <%= image_tag('social-icons/facebook-off.png') %>
        <%= image_tag('social-icons/facebook-on.png') %>
      <% end %>
    </li>
  </ul>
<% end %>